# Read the Docs configuration file
# Ref: https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - html

# Equivalent to:
# $ python -m pip install .[docs]
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
