notifications:
  email:
    recipients:
    - iem244@nyu.edu

sudo: required

language: python

python:
- '2.7'
- '3.5'
- '3.6'

services:
- docker

install:
- pip install -q --no-cache-dir -e .
- travis_wait pip install -q --no-cache-dir -e .

script: #tests
  - pytest tests/test_imports.py
  - pytest -s tests/test_toy_workflow.py
  - pytest -s tests/test_nuisance.py


#build+push under certain contidions
jobs:
  include:
    - stage: docker
          install:
            - echo none
          script:
            - echo none
          deploy:
            provider: script
            script: ./docker_push.sh
            on:
              branch: 
                - master
                - docker-travis-build
              condition: $TRAVIS_PULL_REQUEST = false #push only if not a PR

env: #security
  global:
  - secure: y3whOok8PqzQPfh3c5KxK1qJjBMzIPIvikEFUGe3cb0ZFkYu9e+GgCo+DpnTO5zfVWe/i8rASGY0QWdi83j/UUzALwmC9exSZGZQUmKNcqksipgxPhR1be5aqs3HO4LKuCc44IftkMrov9YAtaN3HhYqRIXet8zIvDjPaCwprBzqONfHGuNWm1tJKZnaalkJVGM8ZnI/ftqjA9/23tVwgFAbVUo/K21nqVE4rm547UrC94XRJldyw/OGFuJ5qjvJG0KvkLsxFNc8uYR+Yfg78R/Y5jw9RQQnG8s8a/WFDm8zMEyMpL82GTGvBJrl14bHHa0swRZDhcyAGiMI5BU7jtvfPetfgf+ijgHMJY/IbkBJoxOSmvYC7edQzUpwkDGGygfw+SSKCg9kXfWPizr8FNcWvE76nZw3fLIupxdlaNqJi0pMRTML2ytwgBgzsePClhcbhx54KvJ5hTXtTUgDOqvEy0mTywRMkW4q67n5VUs3be0TRXGLnGEvtOPjyvFQm00loblwBWZfsXwJi9kilXScesqkLUHioEwfD8/qZp+W1cvLCuZGKt9D1V+0BXk+Iyqh0+nsTJ/3Mw2yeNsz0vsOjLDQFEGR13tcbN0ah7+KI6WF0bYz3pj84O6ULw292gwxML7LmiSTIJ8Xfmj52dFzkCMrDtGv8yujMQ6fCGE=
  - secure: xRJA3sNtIPz8RDrKk+r7fmP8vKW0aIsxlSh35syr77YoKbRRYxkc6bCrxFVs5q9aQuGCeWhivX9uG3Xdr/D22BQY1tGsJepk7Caae4VJY8oPjxDBQzoJ+yfP1bHKJ6rOeJ+xNvkc/YclUglagyUDDgioSlX/9i2887u9Xrc6d3UAOxnIyfK9KfEkqmeNr7dlxewMMCwWJUVlhHPGKOypqqiLhKvPMiCgPEvexKPSoqo7h/05b8Na0jnNUYke/tMt2JdvChseFq6eQsEPvE4JyvnXQSr+boEE27LlDq2rV2GaLxZfE8l7JLptQnJHmV6uDbghgAIXE/Bjb4Lozg9zgLJo9Fk1sggKuSPKD7GGDnz3eBBXwfJ6P1pPCQOKhjMlRdTSNgRoW0Sye2Ht4vwERRA9OTohCYs4zNFI4K+ngh3JcHhSpPg+ttfwXropcVtBlEm+cBtN8lyIRwt0BHf2IIpwsDNQiDk50KkNFkx9+bjdNTD9uRzvxQDS3MAN3tml1vRACPvrK1SBfdmKvNiljDCmcTTmVuEU3L0f1LCiMrUC/TUX7WK9gzOjuTlFZrDjOY/kswL5WwoLzkPqPVDciBxuIysjRLOQKzLALVUZw0LGIH5MOBUpt1lvr/2YHyaDACd4aUVSCN+N4tWCF+duQPAuMTtvfIhL+/xaAj4DmdE=
