notifications:
  email:
    recipients:
    - iem244@nyu.edu
sudo: required
services:
- docker
language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -q --no-cache-dir -e .
- travis_wait pip install -q --no-cache-dir -e .
script:
- pytest tests/test_imports.py
- pytest -s tests/test_toy_workflow.py
- pytest -s tests/test_nuisance.py
jobs:
  include:
  - stage: docker
    install:
    - echo none
    script:
    - echo none
    deploy:
      provider: script
      script: sh docker_push.sh
      on:
        branch: master
        condition: "$TRAVIS_PULL_REQUEST = false"
env:
  global:
  - secure: I5t99RDvZRCpZcbWMXGZ0GCkwguqK8lSVRCuAw7gW9/uhw496bN8ES7+7DpJbMwVOb3MWZvYtAgPzAIIOpudW9dfVu8j1xRn5ggknys7V7O1nhL9LGbunN1mipljr+zM/wGlLBy8yPZk2mlvx/QFD4NHGuZq9wJJ+qVUpzEp1iwBCOB6AqmyXxuQUuwLSQXyJQs+mLUcU3ef1dQiVJxBBGI0XS/NWF71BPzuguiqln3KTaLcYgBWyQGv/cliGKYwFJt1o/LZfLDtxsy4VMDOpUr5vjxQx9BWpk0tlprlH34BCZ/tKjsNj3vXP2WIHn+yXlrbwGu757tNTWXQZs2wdLIqRXguIYCOiWTeHzt6D68lSilfR9fUdXwiy5PxV31OVLm+FFg/XfTf8tL3Bn+SdXjoNwwQ+yx2wlGVXKRvbxvayjvz/TYXmzqxSRtp6m7rg+PWH9fglic/81YpRa7bJsRs0Z8TRMaXgSws7rpsWAnmlatzWOLnUAsQGm37p6XYp5JIyE5mv4HJksopP1XPeRZbrpSbd0J8ro67fbvESBSM2nCkE4xqWaK+E5psz+MQNTxfmpeFqwELHZjCYnlBEr/yirsUrpIPRJUMqDk8TiOiu9DxIi+WIYrV2Wbmn6fPrl5UFE6rM4mXPms/a6dMVxhORATyEQtZ/EOoqmoVIVE=
  - secure: a35RT9KMMQBvT1Qif+oUe109Dc3rza9YHXF89dT0yAMpiWqlYK1+XSv1UuLorBFa7nMrrlFqrFptZzfwZ01VdrgxCCOltE6lyunb/ZNXhHjxJn1nJMnQ7Tw4AuiJYvk5XURCdcLZU9A0s0Oep2PDG3gJF+yGlixgLQzkHZsAGV5fwH500EL5G/9GkdmRmb5KWmIsu2ku/M189hoq7Fz5hoZ4GZ5isVXSZoWOjjZzDpqoZqgpCuD4VkuXo9XwurtFFIcU5I0QRenfTg1ZA2VRtxa0q4WrCOfPRdvCZKRHW/xiE4hFCu4OWXqOwmoqDuCR/ch9pyHcwh42vr8h9WnOznjDE/Eqf70ourbvJIRwDdTbL7kvmi4/BYlmKiamVI59uze5zx7wirF7TnEBmm1fhxI29ndslVFe5Xse1MmrsHbScEztmeY/TcxqKZD67XoK5NxAUiBQtP2pckhuoDSki5yDflQ42kfK8MWT9rB8qSuOB32SC3wwcaMx25KN3H5yq0Jjgjvzr0fInPQVM2X0aZdU1DJGdDM3vsC6C32uhsYeIr4M2t4dgRiqfanluaZf6QqOQYxaEIxvReaQgymu0wSdOt3inTURDnhZXSqAEEKzigefjdsLi2L1+qo3PPH9fFklUXqHBaRVAyTa2a9WjDSyYYvIMSBRJTNDNOzSKmk=
