name: madminer
channels:
- pytorch
- anaconda
- defaults
- conda-ml
dependencies:
- python=3.6.*
- numpy
- h5py
- scipy=1.0.*
- scikit-learn=0.19.*
- matplotlib
- jupyter
- h5py
- six
- pytorch=0.4.*
- bqplot=0.11.0
- pip:
  - uproot
  - scikit-hep
