name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "madminer/**"
      - "setup.py"
  pull_request:
    branches:
      - master
    paths:
      - "docs/**"
      - "madminer/**"
      - "setup.py"

jobs:

  build-docs:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2
    - name: "Set up Python 3.7"
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: "Install Python dependencies"
      run: |
        pip install --no-cache-dir --upgrade pip setuptools wheel
        pip install --no-cache-dir --quiet ".[docs]"
        pip list
    - name: "Build documentation"
      run: |
        cd docs && make html
